image: azul/zulu-openjdk:11

stages:
  - build
  - QA
  - deploy

before_script:
  - chmod +x gradlew

build-jar:
  stage: build
  only:
    - master
  except:
    changes:
      - documents/**/*
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/

sonarqube:
  stage: QA
  except:
    changes:
      - documents/**/*
  script: ./gradlew test sonarqube -Dsonar.host.url=http://sonarqube.ti.howest.be/sonar/ -d

deploy:
  image: debian:latest
  before_script:
    - echo "we don't need gradle or maven anymore"
  stage: deploy
  only:
    - master
  except:
    changes:
      - documents/**/*
  script:
    - apt update -y && apt install -y software-properties-common rename
    - cd build/libs/
    - rename 's/.*\.jar$/mars.jar/' *.jar
    - 'which ssh-agent || apt install -y openssh-client cowsay'
    - PATH="$PATH:/usr/games"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 172.18.18.200 >> ~/.ssh/known_hosts
    - scp -q mars.jar gitlab-runner@172.18.18.200:"/opt/group-${CI_PROJECT_NAMESPACE:(-2)}/mars.jar"
    - ssh gitlab-runner@172.18.18.200 sudo systemctl restart group-${CI_PROJECT_NAMESPACE:(-2)}
    - systemctl -H gitlab-runner@172.18.18.200 status group-${CI_PROJECT_NAMESPACE:(-2)}
  environment: production