openapi: 3.0.0
info:
  title: 'Mars Concept Title'
  description: 'Please complete this spec as seen in the module Information Module'
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: 'Local development implementation'
  - url: https://project-ii.ti.howest.be/mars-23
    description: 'Public web api'
paths:
  /api/message:
    get:
      description: Get a nice message
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string











  /api/colony/{id}:
    get:
      description: get information about the colony with given ID
      operationId: GetColonyByID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string